# Generated by Django 4.1.2 on 2022-12-12 06:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('item_name', models.CharField(max_length=255)),
                ('end_time', models.DateTimeField()),
                ('price_from', models.IntegerField()),
                ('price_end', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('COMPLETED', 'completed'), ('ONGOING', 'ongoing'), (' yet to be  STARTED', 'yet to start')], default='yet to start', max_length=30)),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='winner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
